### PR TITLE
Update apiVersion to support new kubernetes version

### PR DESCRIPTION
**Pull request by wagnst**
Deployment and Ingress need new API version:

Checkout: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

### CODE REVIEW

**Comment by wagnst** [comment]
Also mariadb chart used has `no matches for kind "Deployment" in version "extensions/v1beta1"'`

**Comment by wagnst** [comment]
Switched to bitnami chart, as stable mariadb is dead and not supported anymore.

**Comment by wagnst** [comment]
fixed also the missing new chart var names of mariadb. Deployment is working now:

```
powerdns-helm-56dbd5779f-6ffbk      1/1     Running   2          10m
powerdns-helm-56dbd5779f-6gf2n      1/1     Running   2          10m
powerdns-helm-56dbd5779f-r42wr      1/1     Running   2          10m
powerdns-helm-mariadb-master-0      2/2     Running   0          10m
powerdns-helm-mariadb-slave-0       2/2     Running   0          10m
```

I think its ready for review and merge.

**Comment by andrzejwp** [comment]
Thanks @wagnst I'll review the changes, but this might take a couple of days :(

**Comment by wagnst** [comment]
> Thanks @wagnst I'll review the changes, but this might take a couple of days :(

in the meanwhile I use my fork :-)

**Comment by loktionovam** [comment]
@wagnst Hi! Will these changes be approved?

**Comment by wagnst** [comment]
@loktionovam I have not received any feedback from the @maintainers :-(. I am using my own fork for now.

**Comment by wagnst** [comment]
@andrzejwp any update here? could you review pls?

**Comment by wagnst** [comment]
Hi @andrzejwp any update? You still active?

**Comment by andrzejwp** [comment]
Thanks for the contribution @wagnst and sorry this took so long

**Pull request merged**
